// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Infrastructure.Data;

#nullable disable

namespace NotificationService.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260410054847_NotifyMigration")]
    partial class NotifyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Hi,<br><br>{EmployeeName} has submitted a {LeaveType} request from {StartDate} to {EndDate} ({Days} day(s)).<br>Please review and take action.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Subject = "Leave Request Submitted — {EmployeeName}",
                            Type = "LeaveCreated"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Hi {EmployeeName},<br><br>Your {LeaveType} request from {StartDate} to {EndDate} has been <b>Approved</b>.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Subject = "Your Leave Request has been Approved",
                            Type = "LeaveApproved"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Hi {EmployeeName},<br><br>Your {LeaveType} request has been <b>Rejected</b>.<br>Reason: {Comment}",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Subject = "Your Leave Request has been Rejected",
                            Type = "LeaveRejected"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Hi,<br><br>{EmployeeName} has submitted their timesheet for week starting {WeekStart} ({TotalHours} hours).<br>Please review and approve.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Subject = "Timesheet Submitted for Approval — {EmployeeName}",
                            Type = "TimesheetSubmitted"
                        },
                        new
                        {
                            Id = 5,
                            Body = "Hi {EmployeeName},<br><br>Your timesheet for week starting {WeekStart} has been <b>Approved</b>.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Subject = "Your Timesheet has been Approved",
                            Type = "TimesheetApproved"
                        },
                        new
                        {
                            Id = 6,
                            Body = "Hi {EmployeeName},<br><br>Your timesheet for week starting {WeekStart} has been <b>Rejected</b>.<br>Reason: {Comment}",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Subject = "Your Timesheet has been Rejected",
                            Type = "TimesheetRejected"
                        },
                        new
                        {
                            Id = 7,
                            Body = "Hi {EmployeeName},<br><br>Your timesheet for week starting {WeekStart} has not been submitted yet. Please submit as soon as possible.",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Subject = "Overdue Timesheet Reminder",
                            Type = "TimesheetOverdue"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
